export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const DATA_SUCCESSED = 'DATA_SUCCESSED';
export const DATA_FAILED = 'DATA_FAILED';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

//Auth
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

//Product
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_DETAILS = 'PRODUCT_DETAILS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const ORDER_LIST = 'ORDER_LIST';

export const CATEGORY_LIST = 'CATEGORY_LIST';
